# -*- coding: utf-8 -*-
"""
src/model_bm3.py

BM3 baseline adapted to this project's evaluation pipeline.

Reference:
    BM3: Bootstrap Latent Representations for Multi-modal Recommendation, WWW 2023.

Original BM3 design:
    - Build a normalized user-item interaction graph.
    - Learn user/item ID embeddings through LightGCN-style propagation.
    - Use bootstrap latent target views generated by dropout.
    - Optimize negative-sample-free self-supervised objectives:
        user -> item target alignment
        item -> user target alignment
        text modality -> item target alignment
        vision modality -> item target alignment
        modality self-bootstrap alignment
    - Use full-sort prediction with user/item latent representations.

This implementation:
    - Uses train.txt interactions to build the user-item graph.
    - Supports item ids with padding row 0.
    - Loads text_features.npy and vision_features.npy from processed data dir.
    - Exposes full_sort_scores(user_ids, sequences, lengths) so it can be
      evaluated by the existing project evaluator.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


# ==========================================================
# Feature loading
# ==========================================================


def load_item_feature_matrix(
    data_dir: str | Path,
    feature_file: str,
    num_items: int,
    mask_file: Optional[str] = None,
    normalize: bool = True,
    zero_missing: bool = True,
) -> torch.Tensor:
    """
    Load item feature matrix and align it to shape [num_items + 1, dim].

    The project usually stores item features as:
        [num_items + 1, dim], where row 0 is padding.

    If the file has [num_items, dim], this function prepends a zero padding row.
    """
    data_dir = Path(data_dir)
    feature_path = data_dir / feature_file

    if not feature_path.exists():
        raise FileNotFoundError(f"Feature file not found: {feature_path}")

    arr = np.load(feature_path)
    if arr.ndim != 2:
        raise ValueError(f"Feature file must be 2-D, got shape={arr.shape}: {feature_path}")

    arr = arr.astype(np.float32, copy=False)

    if arr.shape[0] == num_items:
        pad = np.zeros((1, arr.shape[1]), dtype=np.float32)
        arr = np.concatenate([pad, arr], axis=0)
    elif arr.shape[0] > num_items + 1:
        arr = arr[: num_items + 1]
    elif arr.shape[0] < num_items + 1:
        raise ValueError(
            f"Feature rows mismatch for {feature_path}: got {arr.shape[0]}, "
            f"expected {num_items + 1} or {num_items}."
        )

    arr[0] = 0.0

    if mask_file:
        mask_path = data_dir / mask_file
        if mask_path.exists():
            mask = np.load(mask_path).reshape(-1)
            if mask.shape[0] == num_items:
                mask = np.concatenate([np.zeros((1,), dtype=mask.dtype), mask], axis=0)
            elif mask.shape[0] > num_items + 1:
                mask = mask[: num_items + 1]
            elif mask.shape[0] < num_items + 1:
                raise ValueError(
                    f"Mask rows mismatch for {mask_path}: got {mask.shape[0]}, "
                    f"expected {num_items + 1} or {num_items}."
                )

            valid = mask.astype(bool)
            valid[0] = False
            if zero_missing:
                arr[~valid] = 0.0

    x = torch.from_numpy(arr).float()

    if normalize:
        x = F.normalize(x, p=2, dim=-1)
        x = torch.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
        x[0] = 0.0

    return x


# ==========================================================
# Graph construction
# ==========================================================


def build_bm3_norm_adj(
    train_rows: Sequence[Tuple[int, Sequence[int]]],
    num_users: int,
    num_items: int,
    add_self_loops: bool = False,
) -> torch.Tensor:
    """
    Build symmetric normalized adjacency for BM3.

    Node layout:
        user nodes: 0 ... num_users
        item nodes: num_users + 1 ... num_users + num_items + 1

    Padding user 0 and padding item 0 are kept as isolated nodes unless
    add_self_loops=True.
    """
    user_offset = 0
    item_offset = num_users + 1
    n_nodes = (num_users + 1) + (num_items + 1)

    edges: List[Tuple[int, int]] = []

    for uid, seq in train_rows:
        uid = int(uid)
        if uid <= 0 or uid > num_users:
            continue

        # Deduplicate per user to avoid over-weighting repeated interaction rows
        # in the structural graph.
        unique_items = set()
        for item in seq:
            item = int(item)
            if 0 < item <= num_items:
                unique_items.add(item)

        for item in unique_items:
            u_node = user_offset + uid
            i_node = item_offset + item
            edges.append((u_node, i_node))
            edges.append((i_node, u_node))

    if add_self_loops:
        for node in range(n_nodes):
            edges.append((node, node))

    if not edges:
        raise ValueError("No valid train interactions found for BM3 graph.")

    row = np.fromiter((e[0] for e in edges), dtype=np.int64)
    col = np.fromiter((e[1] for e in edges), dtype=np.int64)

    deg = np.bincount(row, minlength=n_nodes).astype(np.float32)
    deg = np.maximum(deg, 1.0)

    values = 1.0 / np.sqrt(deg[row] * deg[col])
    values = values.astype(np.float32)

    indices = torch.from_numpy(np.stack([row, col], axis=0)).long()
    values_t = torch.from_numpy(values).float()

    adj = torch.sparse_coo_tensor(
        indices=indices,
        values=values_t,
        size=(n_nodes, n_nodes),
    )
    adj = adj.coalesce()
    return adj


# ==========================================================
# Loss helpers
# ==========================================================


def cosine_bootstrap_loss(online: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    """
    Negative-sample-free alignment loss:
        1 - mean cosine_similarity(online, stop_gradient(target))
    """
    online = F.normalize(online, p=2, dim=-1)
    target = F.normalize(target.detach(), p=2, dim=-1)

    sim = F.cosine_similarity(online, target, dim=-1)
    sim = torch.nan_to_num(sim, nan=0.0, posinf=0.0, neginf=0.0)
    return 1.0 - sim.mean()


def l2_reg_loss(*tensors: torch.Tensor) -> torch.Tensor:
    if not tensors:
        return torch.tensor(0.0)

    loss = tensors[0].new_tensor(0.0)
    count = 0
    for x in tensors:
        if x is None:
            continue
        loss = loss + x.pow(2).sum()
        count += int(x.numel())
    return loss / max(count, 1)


# ==========================================================
# BM3 model
# ==========================================================


class BM3(nn.Module):
    """
    BM3 multimodal recommendation model.

    Parameters
    ----------
    num_users:
        Maximum real user id. Embedding size is num_users + 1.
    num_items:
        Maximum real item id. Embedding size is num_items + 1.
    norm_adj:
        Sparse normalized user-item adjacency built from train interactions.
    data_dir:
        Processed dataset directory.
    embedding_dim:
        ID graph embedding dimension.
    n_layers:
        LightGCN-style propagation layers.
    dropout:
        Dropout used for bootstrap target view generation.
    reg_weight:
        L2 regularization weight.
    cl_weight:
        Modality contrast / bootstrap weight.
    """

    def __init__(
        self,
        num_users: int,
        num_items: int,
        norm_adj: torch.Tensor,
        data_dir: str | Path,
        embedding_dim: int = 64,
        n_layers: int = 1,
        dropout: float = 0.5,
        reg_weight: float = 0.01,
        cl_weight: float = 1.0,
        text_feature_file: Optional[str] = "text_features.npy",
        vision_feature_file: Optional[str] = "vision_features.npy",
        text_mask_file: Optional[str] = "text_mask.npy",
        vision_mask_file: Optional[str] = "vision_mask.npy",
        use_text: bool = True,
        use_vision: bool = True,
        normalize_features: bool = True,
        zero_missing_features: bool = True,
        freeze_features: bool = False,
        init_std: float = 0.01,
    ) -> None:
        super().__init__()

        if num_users <= 0:
            raise ValueError(f"num_users must be positive, got {num_users}")
        if num_items <= 0:
            raise ValueError(f"num_items must be positive, got {num_items}")
        if embedding_dim <= 0:
            raise ValueError(f"embedding_dim must be positive, got {embedding_dim}")
        if n_layers < 0:
            raise ValueError(f"n_layers must be >= 0, got {n_layers}")
        if not use_text and not use_vision:
            raise ValueError("At least one of use_text/use_vision must be enabled for BM3.")

        self.num_users = int(num_users)
        self.num_items = int(num_items)
        self.embedding_dim = int(embedding_dim)
        self.n_layers = int(n_layers)
        self.dropout = float(dropout)
        self.reg_weight = float(reg_weight)
        self.cl_weight = float(cl_weight)
        self.use_text = bool(use_text)
        self.use_vision = bool(use_vision)

        self.user_node_count = self.num_users + 1
        self.item_node_count = self.num_items + 1
        self.n_nodes = self.user_node_count + self.item_node_count

        if norm_adj.shape != torch.Size([self.n_nodes, self.n_nodes]):
            raise ValueError(
                f"norm_adj shape mismatch: got {tuple(norm_adj.shape)}, "
                f"expected {(self.n_nodes, self.n_nodes)}"
            )

        self.register_buffer("norm_adj", norm_adj.coalesce(), persistent=False)

        self.user_embedding = nn.Embedding(self.num_users + 1, embedding_dim, padding_idx=0)
        self.item_id_embedding = nn.Embedding(self.num_items + 1, embedding_dim, padding_idx=0)
        self.predictor = nn.Linear(embedding_dim, embedding_dim, bias=True)

        self.text_embedding: Optional[nn.Embedding] = None
        self.text_projection: Optional[nn.Linear] = None
        self.vision_embedding: Optional[nn.Embedding] = None
        self.vision_projection: Optional[nn.Linear] = None

        if self.use_text:
            text_feat = load_item_feature_matrix(
                data_dir=data_dir,
                feature_file=str(text_feature_file),
                num_items=num_items,
                mask_file=text_mask_file,
                normalize=normalize_features,
                zero_missing=zero_missing_features,
            )
            self.text_embedding = nn.Embedding.from_pretrained(text_feat, freeze=freeze_features, padding_idx=0)
            self.text_projection = nn.Linear(text_feat.shape[1], embedding_dim, bias=True)

        if self.use_vision:
            vision_feat = load_item_feature_matrix(
                data_dir=data_dir,
                feature_file=str(vision_feature_file),
                num_items=num_items,
                mask_file=vision_mask_file,
                normalize=normalize_features,
                zero_missing=zero_missing_features,
            )
            self.vision_embedding = nn.Embedding.from_pretrained(vision_feat, freeze=freeze_features, padding_idx=0)
            self.vision_projection = nn.Linear(vision_feat.shape[1], embedding_dim, bias=True)

        self.reset_parameters(init_std=init_std)

    def reset_parameters(self, init_std: float = 0.01) -> None:
        nn.init.xavier_uniform_(self.user_embedding.weight)
        nn.init.xavier_uniform_(self.item_id_embedding.weight)
        nn.init.xavier_normal_(self.predictor.weight)
        nn.init.zeros_(self.predictor.bias)

        if self.text_projection is not None:
            nn.init.xavier_normal_(self.text_projection.weight)
            nn.init.zeros_(self.text_projection.bias)

        if self.vision_projection is not None:
            nn.init.xavier_normal_(self.vision_projection.weight)
            nn.init.zeros_(self.vision_projection.bias)

        with torch.no_grad():
            self.user_embedding.weight[0].zero_()
            self.item_id_embedding.weight[0].zero_()
            if self.text_embedding is not None:
                self.text_embedding.weight[0].zero_()
            if self.vision_embedding is not None:
                self.vision_embedding.weight[0].zero_()

    def graph_forward(self) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        LightGCN-style propagation over user-item graph.

        Returns
        -------
        user_g:
            [num_users + 1, embedding_dim]
        item_g:
            [num_items + 1, embedding_dim]
        """
        item_id_weight = self.item_id_embedding.weight
        ego = torch.cat([self.user_embedding.weight, item_id_weight], dim=0)

        all_embeddings = [ego]
        x = ego

        adj = self.norm_adj
        if adj.device != x.device:
            adj = adj.to(x.device)

        for _ in range(self.n_layers):
            x = torch.sparse.mm(adj, x)
            all_embeddings.append(x)

        out = torch.stack(all_embeddings, dim=1).mean(dim=1)
        user_g, item_g = torch.split(out, [self.user_node_count, self.item_node_count], dim=0)

        # Follow BM3 convention: add raw item ID embedding back to propagated item embedding.
        item_g = item_g + item_id_weight

        user_g = torch.nan_to_num(user_g, nan=0.0, posinf=0.0, neginf=0.0)
        item_g = torch.nan_to_num(item_g, nan=0.0, posinf=0.0, neginf=0.0)

        user_g[0] = 0.0
        item_g[0] = 0.0

        return user_g, item_g

    def encode_text_items(self) -> Optional[torch.Tensor]:
        if self.text_embedding is None or self.text_projection is None:
            return None
        z = self.text_projection(self.text_embedding.weight)
        z = torch.nan_to_num(z, nan=0.0, posinf=0.0, neginf=0.0)
        z[0] = 0.0
        return z

    def encode_vision_items(self) -> Optional[torch.Tensor]:
        if self.vision_embedding is None or self.vision_projection is None:
            return None
        z = self.vision_projection(self.vision_embedding.weight)
        z = torch.nan_to_num(z, nan=0.0, posinf=0.0, neginf=0.0)
        z[0] = 0.0
        return z

    def calculate_loss(
        self,
        user_ids: torch.Tensor,
        item_ids: torch.Tensor,
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        """
        BM3 training loss for observed user-item interactions.
        """
        user_ids = user_ids.long()
        item_ids = item_ids.long()

        user_all, item_all = self.graph_forward()

        text_all = self.encode_text_items()
        vision_all = self.encode_vision_items()

        # Target network is stop-gradient dropout view.
        with torch.no_grad():
            user_target = F.dropout(user_all, p=self.dropout, training=self.training)
            item_target = F.dropout(item_all, p=self.dropout, training=self.training)

            text_target = None
            vision_target = None
            if text_all is not None:
                text_target = F.dropout(text_all, p=self.dropout, training=self.training)
            if vision_all is not None:
                vision_target = F.dropout(vision_all, p=self.dropout, training=self.training)

        user_online = self.predictor(user_all)[user_ids]
        item_online = self.predictor(item_all)[item_ids]

        user_t = user_target[user_ids]
        item_t = item_target[item_ids]

        loss_ui = cosine_bootstrap_loss(user_online, item_t)
        loss_iu = cosine_bootstrap_loss(item_online, user_t)

        loss_text_item = user_online.new_tensor(0.0)
        loss_text_self = user_online.new_tensor(0.0)
        loss_vision_item = user_online.new_tensor(0.0)
        loss_vision_self = user_online.new_tensor(0.0)

        if text_all is not None and text_target is not None:
            text_online = self.predictor(text_all)[item_ids]
            text_t = text_target[item_ids]
            loss_text_item = cosine_bootstrap_loss(text_online, item_t)
            loss_text_self = cosine_bootstrap_loss(text_online, text_t)

        if vision_all is not None and vision_target is not None:
            vision_online = self.predictor(vision_all)[item_ids]
            vision_t = vision_target[item_ids]
            loss_vision_item = cosine_bootstrap_loss(vision_online, item_t)
            loss_vision_self = cosine_bootstrap_loss(vision_online, vision_t)

        reg = l2_reg_loss(
            self.user_embedding(user_ids),
            self.item_id_embedding(item_ids),
        )

        rec_loss = loss_ui + loss_iu
        modal_loss = loss_text_item + loss_text_self + loss_vision_item + loss_vision_self
        total = rec_loss + self.cl_weight * modal_loss + self.reg_weight * reg

        total = torch.nan_to_num(total, nan=0.0, posinf=1.0e4, neginf=1.0e4)

        stats = {
            "loss_total": float(total.detach().cpu().item()),
            "loss_rec": float(rec_loss.detach().cpu().item()),
            "loss_ui": float(loss_ui.detach().cpu().item()),
            "loss_iu": float(loss_iu.detach().cpu().item()),
            "loss_modal": float(modal_loss.detach().cpu().item()),
            "loss_text_item": float(loss_text_item.detach().cpu().item()),
            "loss_text_self": float(loss_text_self.detach().cpu().item()),
            "loss_vision_item": float(loss_vision_item.detach().cpu().item()),
            "loss_vision_self": float(loss_vision_self.detach().cpu().item()),
            "loss_reg": float(reg.detach().cpu().item()),
        }

        return total, stats

    def full_sort_scores(
        self,
        user_ids: torch.Tensor,
        sequences: Optional[torch.Tensor] = None,
        lengths: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Full-sort prediction for evaluator compatibility.

        BM3 is graph-based, not sequential, so sequences/lengths are ignored.
        """
        del sequences, lengths

        user_ids = user_ids.long()

        user_all, item_all = self.graph_forward()
        user_online = self.predictor(user_all)
        item_online = self.predictor(item_all)

        scores = torch.matmul(user_online[user_ids], item_online.t())
        scores = torch.nan_to_num(scores, nan=0.0, posinf=0.0, neginf=0.0)
        scores[:, 0] = -1.0e9
        return scores

    def forward(self, user_ids: torch.Tensor, item_ids: torch.Tensor) -> Tuple[torch.Tensor, Dict[str, float]]:
        return self.calculate_loss(user_ids=user_ids, item_ids=item_ids)